# -*- coding: utf-8 -*-
"""Capstone 1 Erika.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8-i2ohYi7nczUdzQU_PkSUlQiXwy9ng
"""

#Utk ambil class datetime dari modul datetime python
from datetime import datetime

#List kosong untuk simpan semua data lead
leads = []

#Dictionary: Ubah nama Dealer jadi kode Dealer
dealer_codes = {
    "Honda Jakarta Center": "HJC",
    "Honda Bandung Center": "HBC",
    "Honda Semarang Center": "HSMC",
    "Honda Surabaya Center": "HSC",
    "Honda Outside Java": "HOJ"
}

#Dictionary: Supaya user tinggal pilih aja (no typo, min effort)
dealer_options = {
    "1": "Honda Jakarta Center",
    "2": "Honda Bandung Center",
    "3": "Honda Semarang Center",
    "4": "Honda Surabaya Center",
    "5": "Honda Outside Java"
}

car_model_options = {
    "1": "Honda Brio",
    "2": "Honda WR-V",
    "3": "Honda BR-V",
    "4": "Honda HR-V",
    "5": "Honda CR-V",
    "6": "Honda Accord",
    "7": "Honda Civic",
    "8": "Honda Step WGN",
    "9": "Honda Prelude"
}

lead_source_options = {
    "1": "Media Sosial",
    "2": "Iklan Digital",
    "3": "Pameran",
    "4": "Billboard",
    "5": "Others"
}

status_options = {
    "1": "Assigned",
    "2": "Contacted",
    "3": "Follow Up",
    "4": "Test Drive",
    "5": "SPK",
    "6": "Lost"
}


#Helper Functions

#Dipakai di Read Lead, Update, Delete
def find_lead_by_id(lead_id):
    for lead in leads:
        if lead["id"] == lead_id:
            return lead
    return None

#Dipakai di Create
def generate_lead_id(dealer_name):
    dealer_code = dealer_codes.get(dealer_name)

    if not dealer_code:
        return None

    max_number = 0

    for lead in leads:
        if lead["dealer"] == dealer_name:
            lead_id = lead["id"]
            number_part = lead_id.split("-")[1]
            number = int(number_part)

            if number > max_number:
                max_number = number

    new_id = f"{dealer_code}-{max_number + 1:03}"
    return new_id

#Dipakai di Helper Choose Lead Source, Create
def input_text_only(prompt):
    while True:
        value = input(prompt).strip()

        if value == "":
            print("Input cannot be empty.")
        elif any(char.isdigit() for char in value):
            print("Invalid input. Use text only, no numbers.")
        else:
            return value

#Dipakai di Update
def input_text_only_optional(prompt):
    while True:
        value = input(prompt).strip()

        if value == "":
            return ""
        elif any(char.isdigit() for char in value):
            print("Invalid input. Use text only, no numbers.")
        else:
            return value

#Dipakai di Create
def input_phone_number():
    while True:
        phone = input("Enter Phone Number: ").strip()

        if phone.isdigit():
            return phone
        else:
            print("Invalid input. Phone number must contain numbers only.")

#Dipakai di Update
def input_phone_number_optional(current_phone):
    while True:
        phone = input(f"Phone Number ({current_phone}): ").strip()

        if phone == "":
            return ""
        elif phone.isdigit():
            return phone
        else:
            print("Invalid input. Phone number must contain numbers only.")

#Dipakai di Create
def input_date():
    while True:
        date_input = input("Enter Entry Date (YYYY-MM-DD): ").strip()

        try:
            valid_date = datetime.strptime(date_input, "%Y-%m-%d")
            return valid_date.strftime("%Y-%m-%d")
        except ValueError:
            print("Invalid date format. Please use YYYY-MM-DD.")

#Dipakai di Update
def input_date_optional(current_date):
    while True:
        date_input = input(f"Entry Date ({current_date}) [YYYY-MM-DD]: ").strip()

        if date_input == "":
            return ""

        try:
            valid_date = datetime.strptime(date_input, "%Y-%m-%d")
            return valid_date.strftime("%Y-%m-%d")
        except ValueError:
            print("Invalid date format. Please use YYYY-MM-DD.")

#Dipakai di Helper Choose Dealer
def show_dealer_list():
    print("\nChoose Dealer:")
    for key, value in dealer_options.items():
        print(f"{key}. {value}")

#Dipakai di Create
def choose_dealer():
    while True:
        show_dealer_list()
        dealer_choice = input("Enter dealer number: ").strip()
        dealer = dealer_options.get(dealer_choice)

        if dealer:
            return dealer
        else:
            print("Invalid dealer choice!")

#Dipakai di Helper Choose Car Model
def show_car_model_list():
    print("\nChoose Car Model:")
    for key, value in car_model_options.items():
        print(f"{key}. {value}")

#Dipakai di Create
def choose_car_model():
    while True:
        show_car_model_list()
        car_choice = input("Enter car model number: ").strip()
        car_model = car_model_options.get(car_choice)

        if car_model:
            return car_model
        else:
            print("Invalid car model choice!")

#Dipakai di Update
def choose_car_model_optional(current_value):
    while True:
        print(f"\nCurrent Car Model: {current_value}")
        show_car_model_list()
        car_choice = input("Enter car model number (leave blank if no change): ").strip()

        if car_choice == "":
            return ""

        car_model = car_model_options.get(car_choice)

        if car_model:
            return car_model
        else:
            print("Invalid car model choice!")

#Dipakai di Helper Choose Lead Source
def show_lead_source_list():
    print("\nChoose Lead Source:")
    for key, value in lead_source_options.items():
        print(f"{key}. {value}")

#Dipakai di Create
def choose_lead_source():
    while True:
        show_lead_source_list()
        source_choice = input("Enter lead source number: ").strip()
        source = lead_source_options.get(source_choice)

        if not source:
            print("Invalid lead source choice!")
            continue

        if source == "Others":
            other_source = input_text_only("Enter Other Lead Source: ")
            return f"Others - {other_source}"
        else:
            return source

#Dipakai di Update
def choose_lead_source_optional(current_value):
    while True:
        print(f"\nCurrent Lead Source: {current_value}")
        show_lead_source_list()
        source_choice = input("Enter lead source number (leave blank if no change): ").strip()

        if source_choice == "":
            return ""

        source = lead_source_options.get(source_choice)

        if not source:
            print("Invalid lead source choice!")
            continue

        if source == "Others":
            other_source = input_text_only("Enter Other Lead Source: ")
            return f"Others - {other_source}"
        else:
            return source

#Dipakai di Helper Choose Status
def show_status_list():
    print("\nChoose Status:")
    for key, value in status_options.items():
        print(f"{key}. {value}")

#Dipakai di Create
def choose_status():
    while True:
        show_status_list()
        status_choice = input("Enter status number: ").strip()
        status = status_options.get(status_choice)

        if status:
            return status
        else:
            print("Invalid status choice!")

#Dipakai di Update
def choose_status_optional(current_value):
    while True:
        print(f"\nCurrent Status: {current_value}")
        show_status_list()
        status_choice = input("Enter status number (leave blank if no change): ").strip()

        if status_choice == "":
            return ""

        status = status_options.get(status_choice)

        if status:
            return status
        else:
            print("Invalid status choice!")

#Dipakai di Helper Show Lead, Add Feat Show Priority Leads
def calculate_lead_score(lead):
    status_scores = {
        "Assigned": 10,
        "Contacted": 20,
        "Follow Up": 30,
        "Test Drive": 40,
        "SPK": 50,
        "Lost": 0
    }

    return status_scores.get(lead["status"], 0)

#Dipakai di Helper Show Lead, Add Feat Show Priority Leads
def recommend_promo(lead):
    if lead["status"] == "Test Drive":
        return "Offer test drive follow-up promo"
    elif lead["status"] == "Follow Up":
        return "Offer limited-time cashback"
    elif lead["car_model"] in ["Honda Brio", "Honda WR-V", "Honda BR-V"]:
        return "Offer first buyer package / accessory package"
    elif lead["car_model"] in ["Honda CR-V", "Honda Accord", "Honda Civic", "Honda Prelude"]:
        return "Offer premium service package"
    else:
        return "Offer general seasonal promo"

#Dipakai di Read
def shorten_text(text, max_length):
    if len(text) <= max_length:
        return text
    return text[:max_length - 3] + "..."

#Dipakai di Read Lead
def show_lead(lead):
    print("-" * 50)
    print(f"Lead ID        : {lead['id']}")
    print(f"Customer       : {lead['customer_name']}")
    print(f"Phone          : {lead['phone']}")
    print(f"Dealer         : {lead['dealer']}")
    print(f"Sales Person   : {lead['sales']}")
    print(f"Car Model      : {lead['car_model']}")
    print(f"Lead Source    : {lead['source']}")
    print(f"Status         : {lead['status']}")
    print(f"Entry Date     : {lead['entry_date']}")
    print(f"Notes          : {lead['notes']}")
    print(f"Lead Score     : {calculate_lead_score(lead)}")
    print(f"Promo Reco     : {recommend_promo(lead)}")


#CRUD Functions
def create_lead():
    dealer = choose_dealer()
    lead_id = generate_lead_id(dealer)

    print(f"\nDealer Selected  : {dealer}")
    print(f"Generated Lead ID: {lead_id}")

    customer_name = input_text_only("Enter Customer Name: ")
    phone = input_phone_number()
    sales = input_text_only("Enter Sales Person Name: ")
    car_model = choose_car_model()
    source = choose_lead_source()
    status = choose_status()
    entry_date = input_date()
    notes = input("Enter Notes: ").strip()

    new_lead = {
        "id": lead_id,
        "customer_name": customer_name,
        "phone": phone,
        "dealer": dealer,
        "sales": sales,
        "car_model": car_model,
        "source": source,
        "status": status,
        "entry_date": entry_date,
        "notes": notes
    }

    leads.append(new_lead)
    print("Lead created successfully!")


def read_all_leads():
    if not leads:
        print("No leads available.")
        return

    print("\nDaftar Leads")
    print("ID        | Customer      | Dealer | Car Model    | Status     | Date")
    print("-" * 72)

    for lead in leads:
        dealer_code = lead["id"].split("-")[0]

        lead_id = shorten_text(lead["id"], 9)
        customer = shorten_text(lead["customer_name"], 13)
        dealer = shorten_text(dealer_code, 6)
        car_model = shorten_text(lead["car_model"], 12)
        status = shorten_text(lead["status"], 10)
        entry_date = shorten_text(lead["entry_date"], 10)

        print(
            f"{lead_id:<9} | "
            f"{customer:<13} | "
            f"{dealer:<6} | "
            f"{car_model:<12} | "
            f"{status:<10} | "
            f"{entry_date:<10}"
        )


def read_lead_by_id():
    lead_id = input("Enter Lead ID to search: ").strip().upper()
    lead = find_lead_by_id(lead_id)

    if lead:
        print("\n===== LEAD DETAIL =====")
        show_lead(lead)
    else:
        print("Lead not found.")


def update_lead():
    lead_id = input("Enter Lead ID to update: ").strip().upper()
    lead = find_lead_by_id(lead_id)

    if not lead:
        print("Lead not found.")
        return

    print("Leave blank if you do not want to change the value.")

    customer_name = input_text_only_optional(f"Customer Name ({lead['customer_name']}): ")
    phone = input_phone_number_optional(lead["phone"])
    sales = input_text_only_optional(f"Sales Person ({lead['sales']}): ")
    car_model = choose_car_model_optional(lead["car_model"])
    source = choose_lead_source_optional(lead["source"])
    status = choose_status_optional(lead["status"])
    entry_date = input_date_optional(lead["entry_date"])
    notes = input(f"Notes ({lead['notes']}): ").strip()

    if customer_name:
        lead["customer_name"] = customer_name
    if phone:
        lead["phone"] = phone
    if sales:
        lead["sales"] = sales
    if car_model:
        lead["car_model"] = car_model
    if source:
        lead["source"] = source
    if status:
        lead["status"] = status
    if entry_date:
        lead["entry_date"] = entry_date
    if notes:
        lead["notes"] = notes

    print("Lead updated successfully!")


def delete_lead():
    lead_id = input("Enter Lead ID to delete: ").strip().upper()
    lead = find_lead_by_id(lead_id)

    if not lead:
        print("Lead not found.")
        return

    leads.remove(lead)
    print("Lead deleted successfully!")



#Additional Feature
def show_priority_leads():
    if not leads:
        print("No leads available.")
        return

    sorted_leads = sorted(leads, key=calculate_lead_score, reverse=True)

    print("\n===== PRIORITY LEADS =====")
    for lead in sorted_leads:
        print(
            f"{lead['id']} | {lead['customer_name']} | "
            f"{lead['dealer']} | Score: {calculate_lead_score(lead)} | "
            f"Promo: {recommend_promo(lead)}"
        )


#Main Menu
def main_menu():
    while True:
        print("\n===== HONDA LEADS TRACKER SYSTEM =====")
        print("1. Create Lead")
        print("2. Read All Leads")
        print("3. Search Lead by ID")
        print("4. Update Lead")
        print("5. Delete Lead")
        print("6. Show Priority Leads")
        print("7. Exit")

        choice = input("Choose menu: ").strip()

        if choice == "1":
            create_lead()
        elif choice == "2":
            read_all_leads()
        elif choice == "3":
            read_lead_by_id()
        elif choice == "4":
            update_lead()
        elif choice == "5":
            delete_lead()
        elif choice == "6":
            show_priority_leads()
        elif choice == "7":
            print("Exiting program...")
            break
        else:
            print("Invalid choice. Please try again.")


#Run Program
main_menu()

